/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p1_TestJNI1 */

#ifndef _Included_p1_TestJNI1
#define _Included_p1_TestJNI1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     p1_TestJNI1
 * Method:    afficherBonjour
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_p1_TestJNI1_afficherBonjour
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
